#!/bin/bash

### BEGIN INIT INFO
# Provides:          servicedesk
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ServiceDesk Plus
# Description:       ServiceDesk Plus init script
### END INIT INFO

# Startup ServiceDesk Plus

# Vladimir Mikhalev
# callvaldemar@gmail.com
# www.heyvaldemar.com

# Put the script in the folder /etc/init.d/ on your ServiceDesk Plus server

INITLOG_ARGS=""

prog="servicedesk"
progname="AdventNet ManageEngine ServiceDesk-Plus"
RETVAL=0
# ServiceDesk Plus install folder (replace with yours)
MDIR=/opt/ServiceDesk/bin

if [ ! -d "$MDIR" ]
then
 echo "Invalid directory $MDIR"
    exit 1
fi

start()
{
        mv -f /var/log/servicedesk-plus.log /var/log/servicedesk-plus1.log
        echo "Starting $progname"
        cd $MDIR
        nohup sh run.sh >/var/log/servicedesk-plus.log 2>&1 &
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch /var/lock/subsys/servicedesk
}

stop()
{
        echo "Stopping $progname"
        cd $MDIR
        sh shutdown.sh -S >>/var/log/servicedesk-plus.log 2>&1
}

case "$1" in
 start)
       start
         ;;
 stop)
      stop
        ;;
    *)
     echo "Usage: $prog {start|stop}"
     exit 1
     ;;
esac

exit $RETVAL
