#!/bin/bash

### BEGIN INIT INFO
# Provides:          servicedesk
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ServiceDesk Plus
# Description:       ServiceDesk Plus init script
### END INIT INFO

# Startup ServiceDesk Plus

# Author
# hey, I’m Vladimir Mikhalev, but my friends call me Valdemar.

# My website with detailed IT guides: https://www.heyvaldemar.com/
# Follow me on YouTube: https://www.youtube.com/channel/UCf85kQ0u1sYTTTyKVpxrlyQ?sub_confirmation=1
# Follow me on Twitter: https://twitter.com/heyValdemar
# Follow me on Instagram: https://www.instagram.com/heyvaldemar/
# Follow me on Facebook: https://www.facebook.com/heyValdemarFB/
# Follow me on TikTok: https://www.tiktok.com/@heyvaldemar
# Follow me on [LinkedIn](https://www.linkedin.com/in/heyvaldemar/)
# Follow me on [GitHub](https://github.com/heyvaldemar)

# Communication
# Chat with IT pros on Discord: https://discord.gg/AJQGCCBcqf
# Reach me at ask@sre.gg

# Give Thanks
# Support on GitHub: https://github.com/sponsors/heyValdemar
# Support on Patreon: https://www.patreon.com/heyValdemar
# Support on BuyMeaCoffee: https://www.buymeacoffee.com/heyValdemar
# Support on Ko-fi: https://ko-fi.com/heyValdemar
# Support on PayPal: https://www.paypal.com/paypalme/heyValdemarCOM

# Put the script in the folder /etc/init.d/ on your ServiceDesk Plus server.

INITLOG_ARGS=""

prog="servicedesk"
progname="AdventNet ManageEngine ServiceDesk-Plus"
RETVAL=0
# ServiceDesk Plus install folder (replace with yours)
MDIR=/opt/ServiceDesk/bin

if [ ! -d "$MDIR" ]
then
 echo "Invalid directory $MDIR"
    exit 1
fi

start()
{
        mv -f /var/log/servicedesk-plus.log /var/log/servicedesk-plus1.log
        echo "Starting $progname"
        cd $MDIR
        nohup sh run.sh >/var/log/servicedesk-plus.log 2>&1 &
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch /var/lock/subsys/servicedesk
}

stop()
{
        echo "Stopping $progname"
        cd $MDIR
        sh shutdown.sh -S >>/var/log/servicedesk-plus.log 2>&1
}

case "$1" in
 start)
       start
         ;;
 stop)
      stop
        ;;
    *)
     echo "Usage: $prog {start|stop}"
     exit 1
     ;;
esac

exit $RETVAL
